version: "3.1"

services:
  db:
    image: postgres:14.2-alpine
    container_name: certifyme_postgres
    restart: always
    environment:
      POSTGRES_DB: certifyme
      POSTGRES_USER: miguel
      POSTGRES_PASSWORD: cincopassaigualadez
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
